### PR TITLE
simple-inventory-system

### PR DESCRIPTION
**Pull request by andreijoshuavalencia**
able to do crud
able to post reviews and reply messages

### CODE REVIEW

**Comment by andreijoshuavalencia** [comment]
issues: 
form validation for login, redirects to error 404 when login info is wrong

**Comment by andreijoshuavalencia** [comment]
> issues: form validation for login, redirects to error 404 when login info is wrong

solved

**Comment by andreijoshuavalencia** [comment]
fully functional

**Comment by imm-industry05** [comment]
> fully functional

nice one, now try to containerize it.

**Pull request closed without merging**
